apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: tenant1
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 8Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: tenant2
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 8Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: tenant3
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 8Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: tenant1  # Change to your namespace
spec:
  limits:
  - default:
      cpu: "500m"   # Default CPU limit (0.5 vCPU)
      memory: "256Mi"  # Default Memory limit
    defaultRequest:
      cpu: "250m"  # Default CPU request (0.25 vCPU)
      memory: "128Mi" # Default Memory request
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: tenant2  # Change to your namespace
spec:
  limits:
  - default:
      cpu: "500m"   # Default CPU limit (0.5 vCPU)
      memory: "256Mi"  # Default Memory limit
    defaultRequest:
      cpu: "250m"  # Default CPU request (0.25 vCPU)
      memory: "128Mi" # Default Memory request
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: tenant3  # Change to your namespace
spec:
  limits:
  - default:
      cpu: "500m"   # Default CPU limit (0.5 vCPU)
      memory: "256Mi"  # Default Memory limit
    defaultRequest:
      cpu: "250m"  # Default CPU request (0.25 vCPU)
      memory: "128Mi" # Default Memory request
    type: Container
